import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useState, useEffect } from 'react';
import { NFC, Ndef, NFCOriginal } from '@awesome-cordova-plugins/nfc';
import { IonButton, IonHeader, IonInput, IonText } from '@ionic/react';
import { Capacitor } from '@capacitor/core';
import { TextHelper } from '@awesome-cordova-plugins/nfc';
import ReadNfc from '../components/ReadNfc'
import WriteNfc from '../components/WriteNfc'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

	return (
		<>
			<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className='' id="lol">Welcome to Remar!</h1>
			<div className='flex flex-col justify-center items-center h-screen text-center'>
			<ReadNfc></ReadNfc>
			<WriteNfc></WriteNfc>
			</div>
		</>
	)
}

//USE THIS CODE NFC PLUGIN https://github.com/escully27/phonegap-nfc-android-12/blob/master/src/android/src/com/chariotsolutions/nfc/plugin/NfcPlugin.java
